#Comment
version: 2.1
orbs:
  release-management: salesforce/npm-release-management@dev:alpha
workflows:
  version: 2
  test-and-release:
    jobs:
      - release-management/test-package:
          name: node-latest
          node_version: latest
          os: windows
